import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

const today = new Date();
const thisYear = today.getFullYear();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-full flex flex-col">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full flex flex-col`}
      >
        <header className="py-2 px-6 flex justify-between dark:bg-gray-700 bg-white shadow-md">
          <h1 className="text-xl dark:text-white text-black">
            Tailwind Practice Site
          </h1>
          <nav>
            <ul className="flex space-x-3">
              <li>
                <a href="#">
                  Home
                </a>
              </li>
              <li>
                <a href="#">
                  Contact
                </a>
              </li>
            </ul>
          </nav>
        </header>

        <SidebarProvider 
          defaultOpen={true}
          side="right"
        > 
          <AppSidebar />
          <main className="flex-grow overflow-auto p-4">
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>

        <footer className="flex-col justify-items-center bg-gray-700">
          <p className="py-3 text-gray-300">
            &copy; Company {thisYear} - All rights reserved
          </p>
        </footer>
      </body>
    </html >
  );
}